Add customized duration unit and small fixes to the bar chart
googleinterns/step189-2020 pull request #44
Opened 2020-09-02 19:22 UTC by LujieZ

This PR adds a customized duration unit based on functions in the 
`duration-utils` and fixes the following issues of the bar chart:

  - `STATE_TO_COLOR` doesn't include all the states, so the
    tooltip's background color is transparent sometimes.
  - The ticks and labels for the boxplot are overlaying each other.
  - The use of `any` in type declaration.

The PR also reformat the `bar-chart.component` to two separate
files to improve code clarity.

2020-09-02 19:26 UTC, LujieZ commented
Current version: https://pr44-56d0e55-dot-step189-2020.uc.r.appspot.com/

2020-09-02 23:29 UTC, razvanm requested changes

2020-09-02 23:29 UTC, razvanm commented on web/src/app/components/bar-chart/bar-chart.utils.ts
> +}
I think we should keep this inside the `bar-chart.component.ts` and imported it from there.

2020-09-03 03:36 UTC, razvanm commented on web/src/app/components/bar-chart/utils.ts
> +export type d3ScaleBand = d3.ScaleBand<string>;
If some of these types are not used I would put keep them in the main file. Another option would be to put them in a separate `types.ts` file.

2020-09-03 03:48 UTC, razvanm approved these changes

2020-09-03 03:53 UTC, merged